name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c release --no-restore
      
    - name: Test
      run: dotnet test -c release --no-build --verbosity normal
    # 代码缺陷分析
    - name: Run InferSharp
      uses: microsoft/infersharpaction@v1.2.1
      id: runinfersharp
      with:
        binary-path: src/Parsifal.Util/bin/Release/net6.0
    # 分析结果输出
    - name: InferSharp analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
